### ISSUE TITLE
Merchant registration not working

### ISSUE THREAD

**Issue by sthamann** [shopwareDowntown/portal#218]
![Screenshot at Apr 01 14-25-59](https://user-images.githubusercontent.com/612626/78137043-e9e58800-7424-11ea-8541-391f07d9adbc.png)

After I have registered as a dealer in the portal, I will receive a confirmation e-mail in English.
When I click on the link, I end up in an English template where the error message "Unfortunately, something went wrong" is displayed.

**Comment by sthamann** [comment]
Hello Not specified testtest,

thank you for your registration at Portal.
Please confirm the registration via the following link:

Completing registration

By this confirmation, you also agree that we may send you further emails as part of the fulfillment of the contract.

**Comment by sthamann** [comment]
this was the mail template

**Comment by shyim** [comment]
On production was the `MERCHANT_PORTAL` env missing
