### ISSUE TITLE
Merchant Order API

### ISSUE THREAD

**Issue by shyim** [shopwareDowntown/portal#240]
* Extend current order api with paging
* Extend current order api with filtering of order state
* Create new detail order api `/merchant-api/v1/order/[ID]`
* Create new api endpoint to mark an order as completed (Order state: done)

**Comment by PaddyS** [comment]
@FloBWer New endpoints:
Order Detail: GET /merchant-api/v1/order/{orderId}
Order Finish: PUT /merchant-api/v1/order/{orderId}/done

Will be done with branch `feature240/extend-order-api`, PR is still to be opened

**Comment by FloBWer** [comment]
Nice, thank you!
